# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Adeptability < Formula
  desc "Cross-harness AI skill portability CLI"
  homepage "https://github.com/itaywol/adeptability"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itaywol/adeptability/releases/download/v1.3.0/adeptability_1.3.0_darwin_amd64.tar.gz"
      sha256 "8a5a8831e8f67355aa160066525fff5b1bb25d3b459afe77efe8bca12445b1a0"

      define_method(:install) do
        bin.install "adept"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itaywol/adeptability/releases/download/v1.3.0/adeptability_1.3.0_darwin_arm64.tar.gz"
      sha256 "148d5ab63475d1b7e5c81b76b6d3f939ad28506dca2c668a30720d41f9b1cb8c"

      define_method(:install) do
        bin.install "adept"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itaywol/adeptability/releases/download/v1.3.0/adeptability_1.3.0_linux_amd64.tar.gz"
      sha256 "85f525bad33d955514f05ea09824ab98a56f64f97c316a47874c24db38cb070c"
      define_method(:install) do
        bin.install "adept"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itaywol/adeptability/releases/download/v1.3.0/adeptability_1.3.0_linux_arm64.tar.gz"
      sha256 "d3302de59f6762ed0d3f85ace0e569c78b46c411fde1bea1303966c446f61c67"
      define_method(:install) do
        bin.install "adept"
      end
    end
  end

  test do
    system "#{bin}/adept", "--version"
  end
end
