# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Adeptability < Formula
  desc "Cross-harness AI skill portability CLI"
  homepage "https://github.com/itaywol/adeptability"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itaywol/adeptability/releases/download/v1.1.0/adeptability_1.1.0_darwin_amd64.tar.gz"
      sha256 "35b87b1687133f84db422a930fa2b810fdea13a8e8d1f63e0b5d432fae9bbd61"

      define_method(:install) do
        bin.install "adept"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itaywol/adeptability/releases/download/v1.1.0/adeptability_1.1.0_darwin_arm64.tar.gz"
      sha256 "edb9af4f2a1b914ddf698842c3939850e8a8318cf6dd850c5196c42cac5b78b4"

      define_method(:install) do
        bin.install "adept"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itaywol/adeptability/releases/download/v1.1.0/adeptability_1.1.0_linux_amd64.tar.gz"
      sha256 "4660edeba1214e0bd580147f1ed36e014dae83ad1c8e7da78f589e757ad30ea3"
      define_method(:install) do
        bin.install "adept"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itaywol/adeptability/releases/download/v1.1.0/adeptability_1.1.0_linux_arm64.tar.gz"
      sha256 "293bfb6f5be8ffcc6c0189aba38cc3c9ef39b737c9d41fe005fc3d19b1ff23d1"
      define_method(:install) do
        bin.install "adept"
      end
    end
  end

  test do
    system "#{bin}/adept", "--version"
  end
end
