# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Adeptability < Formula
  desc "Cross-harness AI skill portability CLI"
  homepage "https://github.com/itaywol/adeptability"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itaywol/adeptability/releases/download/v1.2.0/adeptability_1.2.0_darwin_amd64.tar.gz"
      sha256 "4f47669c4d10586888b2f6fe567d93d66fc154d8c3faa0e8a69239931da3efec"

      define_method(:install) do
        bin.install "adept"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itaywol/adeptability/releases/download/v1.2.0/adeptability_1.2.0_darwin_arm64.tar.gz"
      sha256 "093232c4da2f930b772d6387cf760dcf382fe4089641bde16c5da61f04aec516"

      define_method(:install) do
        bin.install "adept"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itaywol/adeptability/releases/download/v1.2.0/adeptability_1.2.0_linux_amd64.tar.gz"
      sha256 "230b20839e2c6fc80c1cb77f1c8fd6beb817a3c30da56fa4c1ffa5c04632fd2a"
      define_method(:install) do
        bin.install "adept"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itaywol/adeptability/releases/download/v1.2.0/adeptability_1.2.0_linux_arm64.tar.gz"
      sha256 "e246742a9adb69639b70b3a95b551a9157d5e26ea23d27378ed2285efd662cac"
      define_method(:install) do
        bin.install "adept"
      end
    end
  end

  test do
    system "#{bin}/adept", "--version"
  end
end
